name: swim-explorer
dependencies:
  - python
  - pytest
  - pytest-cov
  - pyyaml
  - Flask
  - pip:
    - gunicorn
    - geojson
    - git+https://git@github.com/kjenod/subscription-manager-client.git
    - git+https://git@github.com/kjenod/rest-client.git
    - git+https://git@github.com/kjenod/swim-qpid-proton.git
    - git+https://git@github.com/kjenod/pubsub-facades.git
    - git+https://git@github.com/kjenod/swim-backend.git
    - python-qpid_proton
